# Generated by Django 4.1.4 on 2023-11-04 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academix_Portal', '0008_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.URLField(),
        ),
    ]
