# Generated by Django 4.2.6 on 2023-10-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0003_alter_faculty_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('duedate', models.DateTimeField()),
                ('max_grade', models.IntegerField()),
                ('attachment', models.URLField()),
                ('assignment_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academix_Portal.course')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graded', models.BooleanField(default=False)),
                ('grade', models.IntegerField()),
                ('work', models.URLField()),
                ('feedback', models.CharField(default='Assigned', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academix_Portal.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academix_Portal.student_profile')),
            ],
        ),
    ]
