# Generated by Django 4.2.6 on 2023-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0004_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
