# Generated by Django 4.1.4 on 2023-11-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0010_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='fb',
        ),
    ]
