# Generated by Django 4.1.4 on 2023-11-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0011_rename_feedback_feedback_fb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academix_Portal.faculty_profile'),
        ),
    ]
