# Generated by Django 4.1.4 on 2023-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0012_alter_course_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_profile',
            name='name',
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='first_name',
            field=models.CharField(default='Hi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='last_name',
            field=models.CharField(default='JI', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='middle_name',
            field=models.CharField(default='JI', max_length=20),
            preserve_default=False,
        ),
    ]
