# Generated by Django 4.2.6 on 2023-11-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0013_remove_faculty_profile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('qry', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academix_Portal.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academix_Portal.student_profile')),
            ],
        ),
    ]
