# Generated by Django 4.1.5 on 2023-11-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0014_query'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'assignment')},
        ),
    ]
