# Generated by Django 4.1.5 on 2023-11-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0015_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('name', 'assignment_course')},
        ),
    ]
