# Generated by Django 4.2.6 on 2023-11-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0017_alter_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='work',
            field=models.FileField(upload_to='submissions'),
        ),
    ]
