# Generated by Django 4.2.6 on 2023-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0018_alter_submission_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(upload_to='materials/'),
        ),
    ]
