# Generated by Django 4.2.6 on 2023-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0019_alter_material_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(upload_to=''),
        ),
    ]
