# Generated by Django 4.2.6 on 2023-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academix_Portal', '0021_alter_material_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(max_length=10485760, upload_to='materials'),
        ),
    ]
